In [3]:
!pip install opencv-python

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable


In [1]:
import cv2

In [4]:
import os
os.listdir(".")

['original.png', '.ipynb_checkpoints', 'OpenCV.ipynb']

In [9]:
im_g = cv2.imread("original.png", 0) # 0 - grey scale, 1 - BGR scaler

In [12]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
im_bgr = cv2.imread("original.png", 1)

In [16]:
im_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [18]:
# How to convert numpy array to image

In [21]:
cv2.imwrite("newsmallgrey.png", im_g)

True

In [23]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [28]:
for i in im_g:    # print rows wise
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [31]:
for i in im_g.T: # print column wise
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [35]:
for i in im_g.flat: # prints all the items by making the n-d array flat
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [40]:
#  Stacking(horizontal/vertical) and Splitting numPy arrays

In [42]:
import numpy as np

In [44]:
imh = np.hstack([im_g, im_g])

In [46]:
imh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
print(imh)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [50]:
imv = np.vstack([im_g, im_g, im_g])

In [53]:
print(imv)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [55]:
#  stacking means concatinating -- so diemension should be same if you concatinate 2 or more numpy array objects

In [59]:
# Splitting - horizonatally and vertically -- should provide parameter no of partition, which shuld devide the array equally

In [60]:
imhsh = np.hsplit(imh, 5)

In [63]:
print(imhsh)

[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]


In [65]:
imhv = np.vsplit(imh, 3)

In [68]:
print(imhv)

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]


In [70]:
type(imhv)

list

In [71]:
imhv[0]

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8)